/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simanu;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
public class rakitPC2 extends javax.swing.JInternalFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    static Statement stmt;
    
    public rakitPC2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cmbMotherboard = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("Pilih Motherboard");

        cmbMotherboard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=Pilih=" }));
        cmbMotherboard.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMotherboardItemStateChanged(evt);
            }
        });
        cmbMotherboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMotherboardActionPerformed(evt);
            }
        });
        cmbMotherboard.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbMotherboardPropertyChange(evt);
            }
        });

        jLabel1.setText("Pilih RAM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMotherboard, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(500, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbMotherboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(421, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMotherboardItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMotherboardItemStateChanged

    }//GEN-LAST:event_cmbMotherboardItemStateChanged

    private void cmbMotherboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMotherboardActionPerformed
        if(cmbMotherboard.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Data Belum Lengkap");
        } else {
            conn = simanu.KoneksiDB.simanuDb();

            String cmbMb = (String) cmbMotherboard.getSelectedItem();
            String sql = "SELECT harga_mb, nama_mb FROM motherboard WHERE nama_mb='"+cmbMb+"'";

            try{
                stmt = conn.createStatement();
                rs = stmt.executeQuery(sql);

                while (rs.next()){

                    int hargaMotherboard = rs.getInt("harga_mb");

                    String namaMb = rs.getString("nama_mb");
                    //jLabel3.setText(String.valueOf(hargaMotherboard));
                    //lblMb.setText("1. "+namaMb);
                }
                stmt.close();
                conn.close();
                //jLabel3.setText(cmbMb);
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_cmbMotherboardActionPerformed

    private void cmbMotherboardPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbMotherboardPropertyChange

    }//GEN-LAST:event_cmbMotherboardPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbMotherboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
